#Experiment No.14
#Data Normalization & Data Type Conversion
##Name:Ayush Dumbre
##PRN:25070123029 ;batch:A-2

## A: Data Normalisation

In [ ]:
# Dataset
import pandas as pd
import numpy as np

data ={
    'Product' : ['Laptop','Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price' : [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold' :  [25,60,35,80,50,15],
    'Discount' : [10,15,12,20,18,8]
}

df = pd.DataFrame(data)

print("Original Dataset")
print(df)

Original Dataset
      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

### Min - Max Normalization

In [ ]:
#1. Min - Max Normalization for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nAfter Min-Max Normalization")
print(df[['Product', 'Price', 'Price_MinMax']])

After Min-Max Normalization
      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
# Min - Max Normalization for Units Sold

df['Units_Sold_MinMax'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())

print("\nAfter Min-Max Normalization")
print(df[['Product', 'Units_Sold', 'Units_Sold_MinMax']])

After Min-Max Normalization
      Product  Units_Sold  Units_Sold_MinMax
0      Laptop          25           0.153846
1      Mobile          60           0.692308
2      Tablet          35           0.307692
3  Headphones          80           1.000000
4  Smartwatch          50           0.538462
5      Camera          15           0.000000

In [ ]:
# Min - Max Normalization for Discount

df['Discount_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())

print("\nAfter Min-Max Normalization")
print(df[['Product', 'Discount', 'Discount_MinMax']])

After Min-Max Normalization
      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Mobile        15         0.583333
2      Tablet        12         0.333333
3  Headphones        20         1.000000
4  Smartwatch        18         0.833333
5      Camera         8         0.000000

### Z- Score Normalization

In [ ]:
#2. Z - Score Normalization

df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print("\nAfter Z-Score Normalization")
print(df[['Product', 'Units_Sold', 'Units_Zscore']])

After Z-Score Normalization
      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

### Decimal Scaling

In [ ]:
#3. Decimal  Scaling
# Decimal  Scaling for Price

df['Price_Decimal'] = df['Price'] / 100000

print("\nAfter Decimal Scaling")
print(df[['Product', 'Price', 'Price_Decimal']])

After Decimal Scaling
      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
# Decimal  Scaling for Discount

df['Discount_Zscore'] = df['Discount'] / 100

print("\nAfter Decimal Scaling")
print(df[['Product', 'Discount', 'Discount_Zscore']])

After Decimal Scaling
      Product  Discount  Discount_Zscore
0      Laptop        10             0.10
1      Mobile        15             0.15
2      Tablet        12             0.12
3  Headphones        20             0.20
4  Smartwatch        18             0.18
5      Camera         8             0.08

In [ ]:
# Normalize Multiple Columns

cols = ['Price', 'Units_Sold', 'Discount']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\nNormalised Dataset")
print(df_norm)

Normalised Dataset
      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

## B: Turning Quanlitative Variables into  Quantitative Variables in Python

In [ ]:
data =  {
    'Order_ID' : [101,102,103,104,105,106],
    'Customer_Gender' : ['Male', 'Female', 'Female', 'Male', 'Male', 'Female'],
    'Payment_Method' : ['UPI', 'Credit Card', 'Debit Card', 'COD', 'UPI', "Debit Card"],
    'Product_Category' :  ['Electronics', 'Clothing', 'Home', 'Electronics', 'Beauty','Electronics'],
    'City' : [ 'Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune',  'Hyderabad'],
    'Order_Value' :  [4500, 2300, 3200, 5200, 1800, 4100]
}

df = pd.DataFrame(data)

print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105            Male            UPI           Beauty       Pune
5       106          Female     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
# Method : 1 - Label Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])

print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105            Male            UPI           Beauty       Pune
5       106          Female     Debit Card      Electronics  Hyderabad

   Order_Value  Gender_Label
0         4500             1
1         2300             0
2         3200             0
3         5200             1
4         1800             1
5         4100             0

In [ ]:
# Method 2: One Hot Encoding

df_encoded = pd.get_dummies(df, columns=['Payment_Method'])

print(df_encoded)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105            Male           Beauty       Pune         1800
5       106          Female      Electronics  Hyderabad         4100

   Gender_Label  Payment_Method_COD  Payment_Method_Credit Card  \
0             1               False                       False
1             0               False                        True
2             0               False                       False
3             1                True                       False
4             1               False                       False
5             0               False                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

In [ ]:
# Method 3: Encoding Multiple Columns

df_multi = pd.get_dummies(df, columns=['Product_Category', 'City'])

print(df_multi)

   Order_ID Customer_Gender Payment_Method  Order_Value  Gender_Label  \
0       101            Male            UPI         4500             1
1       102          Female    Credit Card         2300             0
2       103          Female     Debit Card         3200             0
3       104            Male            COD         5200             1
4       105            Male            UPI         1800             1
5       106          Female     Debit Card         4100             0

   Product_Category_Beauty  Product_Category_Clothing  \
0                    False                      False
1                    False                       True
2                    False                      False
3                    False                      False
4                     True                      False
5                    False                      False

   Product_Category_Electronics  Product_Category_Home  City_Bangalore  \
0                          True                  False           False
1                         False                  False           False
2                         False                   True           False
3                          True                  False            True
4                         False                  False           False
5                          True                  False           False

   City_Delhi  City_Hyderabad  City_Mumbai  City_Pune
0       False           False        False       True
1       False           False         True      False
2        True           False        False      False
3       False           False        False      False
4       False           False        False       True
5       False            True        False      False

In [ ]:
# Method 4: Dummy Encoding (By Default it drops the first  column)

df_dummy = pd.get_dummies(df, columns = ['Payment_Method'], drop_first = True)

print(df_dummy)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105            Male           Beauty       Pune         1800
5       106          Female      Electronics  Hyderabad         4100

   Gender_Label  Payment_Method_Credit Card  Payment_Method_Debit Card  \
0             1                       False                      False
1             0                        True                      False
2             0                       False                       True
3             1                       False                      False
4             1                       False                      False
5             0                       False                       True

   Payment_Method_UPI
0                True
1               False
2               False
3               False
4                True
5               False

## Data Normalization in Amazon Dataset

In [ ]:
# Data Normalization

import pandas as pd
import numpy as np

df = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
# Normalize Multiple Columns using Min - Max Method

cols = ['Price', 'Rating', 'Reviews', 'Units_Sold']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\nNormalised Dataset")
print(df_norm)

Normalised Dataset
       Price    Rating   Reviews  Units_Sold
0   0.020243  0.428571  0.291005    0.518519
1   0.048583  0.714286  0.148148    0.277778
2   0.016194  0.142857  0.119048    0.203704
3   0.089069  0.857143  0.444444    0.629630
4   0.149798  0.571429  0.695767    0.833333
5   0.036437  0.285714  0.351852    0.592593
6   0.024291  0.000000  0.052910    0.129630
7   0.064777  0.428571  0.185185    0.351852
8   0.210526  1.000000  0.378307    0.481481
9   0.028340  0.285714  0.089947    0.222222
10  0.311741  0.857143  1.000000    1.000000
11  0.174089  0.714286  0.444444    0.407407
12  0.052632  0.571429  0.232804    0.500000
13  0.016194  0.142857  0.031746    0.092593
14  0.024291  0.285714  0.119048    0.240741
15  0.251012  0.857143  0.497354    0.444444
16  0.036437  0.428571  0.089947    0.259259
17  0.068826  0.571429  0.312169    0.648148
18  0.109312  0.714286  0.814815    0.851852
19  0.040486  0.428571  0.148148    0.351852
20  0.008097  0.000000  0.000000    0.148148
21  0.089069  0.571429  0.272487    0.444444
22  0.352227  0.857143  0.219577    0.185185
23  0.020243  0.285714  0.079365    0.259259
24  0.129555  0.714286  0.444444    0.592593
25  0.174089  0.571429  0.148148    0.166667
26  0.514170  1.000000  0.708995    0.129630
27  0.076923  0.428571  0.232804    0.370370
28  0.016194  0.285714  0.121693    0.314815
29  0.048583  0.428571  0.150794    0.351852
30  0.392713  0.857143  0.444444    0.240741
31  0.230769  0.714286  0.351852    0.203704
32  0.129555  0.571429  0.550265    0.666667
33  0.473684  0.857143  0.272487    0.092593
34  0.635628  1.000000  0.444444    0.037037
35  0.012146  0.142857  0.007937    0.166667
36  0.020243  0.285714  0.126984    0.462963
37  0.000000  0.000000  0.047619    0.574074
38  0.028340  0.428571  0.079365    0.259259
39  0.048583  0.571429  0.026455    0.111111
40  0.109312  0.714286  0.113757    0.148148
41  0.433198  0.857143  0.206349    0.074074
42  0.190283  0.571429  0.444444    0.351852
43  1.000000  1.000000  0.365079    0.000000
44  0.068826  0.428571  0.259259    0.444444
45  0.311741  0.857143  0.470899    0.240741
46  0.757085  0.714286  0.325397    0.092593
47  0.089069  0.571429  0.148148    0.185185
48  0.129555  0.428571  0.119048    0.148148
49  0.028340  0.285714  0.089947    0.314815

In [ ]:
# Normalise Multiple Columns with Z Score Method

df_Zscore = (df[cols] - df[cols].mean()) / df[cols].std()

print("\nAfter Z-Score Normalization")
print(df_Zscore)

After Z-Score Normalization
       Price    Rating   Reviews  Units_Sold
0  -0.692019 -0.421580  0.075943    0.812282
1  -0.557310  0.606665 -0.577069   -0.260855
2  -0.711263 -1.449825 -0.710090   -0.591051
3  -0.364869  1.120787  0.777327    1.307576
4  -0.076207  0.092542  1.926145    2.215615
5  -0.615043 -0.935703  0.354078    1.142478
6  -0.672775 -1.963948 -1.012411   -0.921247
7  -0.480334 -0.421580 -0.407770    0.069341
8   0.212455  1.634910  0.475006    0.647184
9  -0.653531 -0.935703 -0.843111   -0.508502
10  0.693559  1.120787  3.316819    2.958556
11  0.039258  0.606665  0.777327    0.316988
12 -0.538066  0.092542 -0.190099    0.729733
13 -0.711263 -1.449825 -1.109154   -1.086345
14 -0.672775 -0.935703 -0.710090   -0.425953
15  0.404897  1.120787  1.019183    0.482086
16 -0.615043 -0.421580 -0.843111   -0.343404
17 -0.461090  0.092542  0.172685    1.390125
18 -0.268648  0.606665  2.470321    2.298164
19 -0.595799 -0.421580 -0.577069    0.069341
20 -0.749752 -1.963948 -1.254267   -0.838698
21 -0.364869  0.092542 -0.008707    0.482086
22  0.886000  1.120787 -0.250563   -0.673600
23 -0.692019 -0.935703 -0.891483   -0.343404
24 -0.172428  0.606665  0.777327    1.142478
25  0.039258  0.092542 -0.577069   -0.756149
26  1.655766  1.634910  1.986609   -0.921247
27 -0.422601 -0.421580 -0.190099    0.151890
28 -0.711263 -0.935703 -0.697998   -0.095757
29 -0.557310 -0.421580 -0.564977    0.069341
30  1.078442  1.120787  0.777327   -0.425953
31  0.308676  0.606665  0.354078   -0.591051
32 -0.172428  0.092542  1.261039    1.472674
33  1.463325  1.120787 -0.008707   -1.086345
34  2.233090  1.634910  0.777327   -1.333992
35 -0.730508 -1.449825 -1.217989   -0.756149
36 -0.692019 -0.935703 -0.673812    0.564635
37 -0.788240 -1.963948 -1.036597    1.059929
38 -0.653531 -0.421580 -0.891483   -0.343404
39 -0.557310  0.092542 -1.133339   -1.003796
40 -0.268648  0.606665 -0.734276   -0.838698
41  1.270883  1.120787 -0.311027   -1.168894
42  0.116235  0.092542  0.777327    0.069341
43  3.965063  1.634910  0.414542   -1.499090
44 -0.461090 -0.421580 -0.069171    0.482086
45  0.693559  1.120787  0.898255   -0.425953
46  2.810415  0.606665  0.233150   -1.086345
47 -0.364869  0.092542 -0.577069   -0.673600
48 -0.172428 -0.421580 -0.710090   -0.838698
49 -0.653531 -0.935703 -0.843111   -0.095757

In [ ]:
# Normalization using Decimal Scaling Method

col1 = ['Price', 'Reviews']

df_DecimalScale = df[col1] / 10000

print("\nAfter Decimal Scaling")
print(df_DecimalScale)

After Decimal Scaling
     Price  Reviews
0   0.0799    0.152
1   0.1499    0.098
2   0.0699    0.087
3   0.2499    0.210
4   0.3999    0.305
5   0.1199    0.175
6   0.0899    0.062
7   0.1899    0.112
8   0.5499    0.185
9   0.0999    0.076
10  0.7999    0.420
11  0.4599    0.210
12  0.1599    0.130
13  0.0699    0.054
14  0.0899    0.087
15  0.6499    0.230
16  0.1199    0.076
17  0.1999    0.160
18  0.2999    0.350
19  0.1299    0.098
20  0.0499    0.042
21  0.2499    0.145
22  0.8999    0.125
23  0.0799    0.072
24  0.3499    0.210
25  0.4599    0.098
26  1.2999    0.310
27  0.2199    0.130
28  0.0699    0.088
29  0.1499    0.099
30  0.9999    0.210
31  0.5999    0.175
32  0.3499    0.250
33  1.1999    0.145
34  1.5999    0.210
35  0.0599    0.045
36  0.0799    0.090
37  0.0299    0.060
38  0.0999    0.072
39  0.1499    0.052
40  0.2999    0.085
41  1.0999    0.120
42  0.4999    0.210
43  2.4999    0.180
44  0.1999    0.140
45  0.7999    0.220
46  1.8999    0.165
47  0.2499    0.098
48  0.3499    0.087
49  0.0999    0.076

## Converting Categrical Data to Quantitative using External Dataset

In [ ]:
# Import Dataset

df1 = pd.read_csv('/content/Student-Dataset.csv')
df1

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
# Label Encoding for Placements

df1['Placement_Status_quant'] = le.fit_transform(df1['Placement_Status'])

print(df1)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Status_quant
0                     92           Placed  450000                       1
1                     85       Not Placed       0                       0
2                     96           Placed  550000                       1
3                     78       Not Placed       0                       0
4                     88           Placed  480000                       1
5                     72       Not Placed       0                       0
6                     91           Placed  500000                       1
7                     80       Not Placed       0                       0
8                     84           Placed  420000                       1
9                     76       Not Placed       0                       0

In [ ]:
# One hot Encoding For Placements

df1_encoded = pd.get_dummies(df1, columns=['Placement_Status'])

print(df1_encoded)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage  Salary  Placement_Status_quant  \
0                     92  450000                       1
1                     85       0                       0
2                     96  550000                       1
3                     78       0                       0
4                     88  480000                       1
5                     72       0                       0
6                     91  500000                       1
7                     80       0                       0
8                     84  420000                       1
9                     76       0                       0

   Placement_Status_Not Placed  Placement_Status_Placed
0                        False                     True
1                         True                    False
2                        False                     True
3                         True                    False
4                        False                     True
5                         True                    False
6                        False                     True
7                         True                    False
8                        False                     True
9                         True                    False

In [ ]:
# Dummies for Department

df1_dummy = pd.get_dummies(df1, columns = ['Department'], drop_first = True)

print(df1_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_quant  Department_Computer  \
0           Placed  450000                       1                 True
1       Not Placed       0                       0                False
2           Placed  550000                       1                False
3       Not Placed       0                       0                False
4           Placed  480000                       1                 True
5       Not Placed       0                       0                False
6           Placed  500000                       1                False
7       Not Placed       0                       0                 True
8           Placed  420000                       1                False
9       Not Placed       0                       0                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True